apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: embedbase-db-1024
spec:
  instances: 1

  imageName: 'ghcr.io/cloudnative-pg/postgresql:16.6'

  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: embedbase
      owner: embedbase
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;

  resources:
    requests:
      memory: "1024Mi"
      cpu: 500m
    limits:
      memory: "4096Mi"
      cpu: 1

  storage:
    size: 10Gi
    storageClass: zfs-csi
